# restores:
#   - name: example
#     namespace: default
#     dbAppConfig: cluster-example-app
#     resticSecretName: restic-secret
#     doCleanup: true # cleanup db before restore
#     snapshotID: latest
#     jobIteration: 1

imagePullPolicy: IfNotPresent
image:
  pullPolicy: IfNotPresent
  repo: ghcr.io/haosgames/restic-pg-dump-docker
  tag: latest
