{{- range $i, $value := .Values.backups }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup-{{ $value.name }}
  namespace: {{ $value.namespace }}
spec:
  schedule: {{ $value.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic-backup
            image: ghcr.io/haosgames/restic-pg-dump-docker:latest
            imagePullPolicy: IfNotPresent
            command:
            - backup.sh
            envFrom:
            - secretRef:
                name: {{ $value.resticSecretName }}
            env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ $value.dbAppConfig }}
                  key: host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ $value.dbAppConfig }}
                  key: port
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ $value.dbAppConfig }}
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $value.dbAppConfig }}
                  key: password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $value.dbAppConfig }}
                  key: dbname
            - name: RESTIC_KEEP_HOURLY
              value: '{{ ($value.resticKeep).hourly | default "24" }}'
            - name: RESTIC_KEEP_DAILY
              value: '{{ ($value.resticKeep).daily | default "7" }}'
            - name: RESTIC_KEEP_WEEKLY
              value: '{{ ($value.resticKeep).weekly | default "4" }}'
            - name: RESTIC_KEEP_MONTHLY
              value: '{{ ($value.resticKeep).monthly | default "12" }}'
            - name: RESTIC_KEEP_YEARLY
              value: '{{ ($value.resticKeep).yearly | default "4" }}'
          restartPolicy: OnFailure
{{- end }}
