name: CI/CD

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io/haosgames
        username: haosgames
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Docker image tag
      id: set-tag
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
      run: |
        # Build with both specific tag and latest tag
        docker build -t ghcr.io/haosgames/restic-pg-dump-docker:${{ env.IMAGE_TAG }} .
        docker push ghcr.io/haosgames/restic-pg-dump-docker:${{ env.IMAGE_TAG }}
        
        # If this is the master branch, also tag as latest
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          docker tag ghcr.io/haosgames/restic-pg-dump-docker:${{ env.IMAGE_TAG }} ghcr.io/haosgames/restic-pg-dump-docker:latest
          docker push ghcr.io/haosgames/restic-pg-dump-docker:latest
        fi

  push-helmchart:
    # Only run for semantic version tags
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Backup Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.5.0
      with:
        name: pg-dump-restic-backup-chart
        repository: haosgames/restic-pg-dump-docker
        tag: ${{ github.ref_name }}
        path: charts/backup
        registry: ghcr.io
        registry_username: hasgames
        registry_password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Restore Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.5.0
      with:
        name: pg-restore-restic-backup-chart
        repository: haosgames/restic-pg-dump-docker
        tag: ${{ github.ref_name }}
        path: charts/restore
        registry: ghcr.io
        registry_username: hasgames
        registry_password: ${{ secrets.GITHUB_TOKEN }}
