name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io/haosgames
        username: haosgames
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/haosgames/restic-pg-dump-docker:latest .
        docker push ghcr.io/haosgames/restic-pg-dump-docker:latest

  push-helmchart:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Backup Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.5.0
      with:
        name: pg-dump-restic-backup-chart
        repository: haosgames/restic-pg-dump-docker
        tag: 0.1.0
        path: charts/backup # Default charts/{name}
        registry: ghcr.io
        registry_username: hasgames
        registry_password: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.5.0
      with:
        name: pg-restore-restic-backup-chart
        repository: haosgames/restic-pg-dump-docker
        tag: 0.1.0
        path: charts/restore # Default charts/{name}
        registry: ghcr.io
        registry_username: hasgames
        registry_password: ${{ secrets.GITHUB_TOKEN }}